dist: xenial
language: python
python:
  - "3.7"
branches:
  only:
    - master
install:
  - pip install --no-cache-dir --editable=".[cpu,dev]"
script:
  - travis_wait pytest
  - cd guide && bash .run_tests.sh
