dist: xenial
language: python
python:
  - "3.6"
branches:
  only:
    - master
install:
  - pip install --no-cache-dir --editable=".[dev]" tf-nightly
script:
  - pytest --verbose --cov=nobrainer nobrainer
