dist: focal
language: python
python:
  - "3.8"
branches:
  only:
    - master
install:
  - python -m pip install --no-cache-dir --upgrade pip setuptools wheel
  - python -m pip install --no-cache-dir --editable=".[cpu,dev]"
script:
  - flake8
  - travis_wait pytest nobrainer
  - cd guide && bash .run_notebooks.sh
