dist: xenial
language: python
python:
  - "3.6"
branches:
  only:
    - master
install:
  - pip install --no-cache-dir --editable=".[cpu,dev]"
script:
  - travis_wait pytest --verbose --cov=nobrainer nobrainer
