---

version: 2
jobs:

  build:
    docker:
      - image: kaczmarj/nobrainer:enh_stabilize
    steps:
      - checkout:
          path: /home/circleci/nobrainer
      - run:
          name: Install nobrainer and dependencies
          command: |
            pip uninstall -y tensorflow-gpu
            pip install --no-cache-dir -e /home/circleci/nobrainer[cpu]
            pip install --no-cache-dir pytest-cov
      - run:
          name: Run tests
          working_directory: /home/circleci/nobrainer
          command: |
            pytest --cov=./
            bash <(curl -s https://codecov.io/bash)
