---

version: 2
jobs:

  build:
    docker:
      - image: circleci/python:3.6.4-stretch-browsers
    steps:
      - checkout:
          path: /home/circleci/nobrainer
      - run:
          name: Install nobrainer and dependencies for tests
          command: |
            pip install --user --no-cache-dir -U pip
            pip install --user --no-cache-dir -q -e /home/circleci/nobrainer[cpu]
            pip install --user --no-cache-dir -q codecov pytest-cov
      - run:
          name: Run tests
          working_directory: /home/circleci/nobrainer
          command: |
            export PATH="~/.local/bin:$PATH"
            pytest --cov=nobrainer nobrainer
      - run:
          name: Upload coverage results
          working_directory: /home/circleci/nobrainer
          command: |
            export PATH="~/.local/bin:$PATH"
            ls -a
            bash <(curl -s https://codecov.io/bash)
